local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

google:
  service: GCS
  credentials: <%= Rails.root.join("config/keys/keyfile.json") %>
  project: esaas-404917
  bucket: boxt-storage
